version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: mysql
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
